# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: dark
  color: blue

style:
  custom_css: ["css/custom.css"]

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: ''
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "left"
    fixed_to_top: true
    logo:
      text: ""
      # Logo filename in `assets/media/` folder
      filename: "logo_test.png"
    #button:
    #  enable: true
    #  text: "Get Started"
    #  url: "https://hugoblox.com/templates/"
    show_search: true
    show_theme_chooser: false

# Site footer
footer:
  copyright:
    notice: 'Â© {year} Daniel Ospina Pajoy'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
